### ISSUE TITLE
Error: Should pass a string with slash separator, like a folder tree path

### ISSUE THREAD

**Issue by luizeboli** [ipetinate/clingon#33]
## Input values

│ Framework/Lib        │ 'react'                              │
│ Resource Type        │ 'component'                          │
│ Resource Name        │ 'Felicio'                            │
│ With TypeScript      │ 'Yes'                                │
│ CSS approach         │ 'Tailwind Inline (inside component)' │
│ With Story           │ 'No'                                 │
│ With Unit Test       │ 'Yes'                                │
│ With Testing Library │ 'Yes'                                │
│ My Test Postfix      │ 'spec'                               │
│ My Test Framework    │ 'vitest'                             │
│ Resource Path        │ 'src/components'                     │
│ Test Path            │ 'src/__tests__'                      │

It throws an error `Error: Should pass a string with slash separator, like a folder tree path`, and just creates the component file

Node.js v20.11.0

**Comment by ipetinate** [comment]
I was debugging and analyzing the mentioned problem, and I didn't find anything necessarily wrong with the generators or the element creation logic, what I found wrong was the lack of validation in the style file generator, where it didn't get the path of the template for cases where the selected style was "Tailwind Inline" which does not have a css file. In this case, it ended up giving an error when trying to validate the template path (which was undefined/null).

I'm uploading the correction in PR #34, already published with version 0.7.2

Ref: [Line with fix on PR #34](https://github.com/ipetinate/clingon/pull/34/files#diff-a29495844064694abea16c83e99c2ca3ff807f2aa27b28cf1e2b194a7719ededR22)

**Comment by ipetinate** [comment]
In addition to the error mentioned above, I found a bug in the composition of the path array for the method that checks if the path exists, and this method always expects an array. I had added validation for paths with "." but it was not available for paths without nesting, such as "components" (instead of "src/components"), so in this scenario it could not find a "/" in the path string and threw the exception.

The issue was fixed in version 0.7.3

## Pull Request

#35 

## Release

```shell
npx clingon@0.7.3 gen
```

## Reference

[Line with issue fix](https://github.com/ipetinate/clingon/pull/35/files#diff-b1d4eb1cf7dfea728eeee34485ecd953881224bb12d573f054d8f33b0669cd84R9)

## Preview

- Not nested paths w/ limited options

<img width="1840" alt="Screenshot 2024-05-02 at 06 11 48" src="https://github.com/ipetinate/clingon/assets/15758789/b73ad990-fb19-4c72-91b0-11184c9d6e12">

- Nested paths w/ full options

<img width="1840" alt="Screenshot 2024-05-02 at 06 15 55" src="https://github.com/ipetinate/clingon/assets/15758789/20c7137a-145f-48b0-ad61-3a273ab953ef">

**Comment by ipetinate** [comment]
@luizeboli If you can test the release and mark the issue as closed... :D
